export const {
	VITE_APP_TITLE: APP_TITLE,
	VITE_FIREBASE_API_URL: FIREBASE_API_URL,
	VITE_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
	VITE_FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID,
	VITE_FIREBASE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
	VITE_FIREBASE_MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
	VITE_FIREBASE_APP_ID: FIREBASE_APP_ID,
} = import.meta.env
